global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node1:9100', 'node2:9100']
