apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node1
        image: hassanatic/ds_project-node1:latest
        #imagePullPolicy: Never
